name: Test

on:
  workflow_dispatch: {}
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-gcc
        name: Set up GCC
        run: sudo dnf install -y gcc valgrind meson python3
      - id: test
        name: Run test
        run: |
          meson setup build -Dtests=true -Dc_args=-DCI_TEST=true -Dc_std=gnu2x
          meson compile -C build
          meson test -C build --verbose --wrapper "valgrind --leak-check=full --error-exitcode=1 -s"
