name: Test

on:
  workflow_dispatch: {}
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-gcc
        name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - id: setup-valgrind
        name: Set up Valgrind
        run: sudo apt install -y build-essential valgrind
      # TODO: use https://github.com/marketplace/actions/changed-files to
      # only check changed files
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install meson ninja
      - id: test
        name: Run test
        run: |
          meson setup build -Dtests=true -Dc_args=-DCI_TEST=true -Dc_std=gnu2x
          meson compile -C build
          meson test -C build --verbose --wrapper "valgrind --leak-check=full --error-exitcode=1 -s"
